### ISSUE TITLE
`for/all` that does nothing shouldnt change type

### ISSUE THREAD

**Issue by stchang** [stchang/typed-rosette#15]
I would expect the type to remain the same. Is this intentional or accidental behavior?

```racket
(define-type-alias TermIntorFalse (U CFalse (Term CInt)))

(define-symbolic i integer?)
(define-symbolic b boolean?)

(define term-int-or-false (if b #f (+ i 1)))

(ann (for/all ([x term-int-or-false]) x) : TermIntorFalse) ; ERR
```

**Comment by stchang** [comment]
More specifically, why does `type-merge` of `CFalse` and `CFalse` produce `(Term CFalse)`?

**Comment by AlexKnauth** [comment]
For `CFalse` it's okay to produce `CFalse`, but that's not true for most types. It's only true here because `CFalse` is a singleton type, and "every member" of `CFalse` is eq to "every other member". We could put in special cases for `CFalse` and `CTrue`.

We can't even do it for `CZero`, because expressions like `(if b 0 0.0)` and `(if b 0.0 -0.0)` produce symbolic terms.

**Comment by stchang** [comment]
Yes, that's why we got rid of `CZero`

**Comment by AlexKnauth** [comment]
The specific cases of `CFalse` and `CTrue` being wrapped in terms are fixed now.

**Comment by stchang** [comment]
fixed in https://github.com/stchang/typed-rosette/commit/56e2177c80429564e1b376951a3b1d2f333cc46b
